import tensorflow as tf
import numpy as np

# --- 1. CONFIGURATION ---
# These must exactly match your train_model.py settings
FRAME_LENGTH = 640
FFT_LENGTH = 1024
NUM_SPECTROGRAM_BINS = FFT_LENGTH // 2 + 1  # 513 bins
NUM_MEL_BINS = 40
SAMPLE_RATE = 16000

print("Generating tensors...")

# --- 2. GENERATE TENSORS ---
# Get the Hann Window
hann_window = tf.signal.hann_window(FRAME_LENGTH, periodic=True).numpy()

# Get the Mel Filterbank Matrix
mel_matrix = tf.signal.linear_to_mel_weight_matrix(
    num_mel_bins=NUM_MEL_BINS,
    num_spectrogram_bins=NUM_SPECTROGRAM_BINS,
    sample_rate=SAMPLE_RATE,
    lower_edge_hertz=20.0,
    upper_edge_hertz=4000.0
).numpy()

# --- 3. EXPORT TO C HEADER ---
header_filename = "mel_constants.h"
print(f"Writing to {header_filename}...")

with open(header_filename, "w") as f:
    f.write("/* AUTO-GENERATED BY TENSORFLOW EXPORT SCRIPT */\n")
    f.write("#ifndef MEL_CONSTANTS_H\n")
    f.write("#define MEL_CONSTANTS_H\n\n")
    f.write("#include <stdint.h>\n\n")
    
    # 3A. Write Hann Window
    f.write(f"// Hann Window for STFT\n")
    f.write(f"// Length: {FRAME_LENGTH}\n")
    f.write(f"const float HANN_WINDOW[{FRAME_LENGTH}] = {{\n")
    
    # Format floats cleanly, 10 per line
    hann_vals = [f"{val:.6f}f" for val in hann_window]
    for i in range(0, len(hann_vals), 10):
        f.write("    " + ", ".join(hann_vals[i:i+10]) + ",\n")
    f.write("};\n\n")
    
    # 3B. Write Mel Matrix
    f.write(f"// Mel Filterbank Matrix\n")
    f.write(f"// Rows (Spectrogram Bins): {NUM_SPECTROGRAM_BINS}\n")
    f.write(f"// Cols (Mel Bins): {NUM_MEL_BINS}\n")
    f.write(f"// Note: Stored as a flat, row-major 1D array for CMSIS-DSP arm_mat_mult_f32\n")
    
    # Flatten the 2D matrix to 1D
    mel_flat = mel_matrix.flatten()
    f.write(f"const float MEL_MATRIX[{len(mel_flat)}] = {{\n")
    
    mel_vals = [f"{val:.6f}f" for val in mel_flat]
    for i in range(0, len(mel_vals), 10):
         f.write("    " + ", ".join(mel_vals[i:i+10]) + ",\n")
    f.write("};\n\n")
    
    f.write("#endif // MEL_CONSTANTS_H\n")

print("✅ Success! You can now copy 'mel_constants.h' into your STM32CubeIDE project.")